baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Arjun Pitchanathan'

# No tags/categories on this site; disable default taxonomies.
[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
